{"name": "test_openai_adapter_authentication_error", "status": "passed", "description": "Test OpenAI adapter handles 401 authentication errors.", "attachments": [{"name": "log", "source": "7214ccf3-1fe6-4927-924b-284e648388e0-attachment.txt", "type": "text/plain"}], "start": 1757668143802, "stop": 1757668143802, "uuid": "6a569cf1-7ef6-4b8b-94a4-dfb3ae26cef8", "historyId": "3cddc73f16fe29d39bdbf3d11652e1e9", "testCaseId": "3cddc73f16fe29d39bdbf3d11652e1e9", "fullName": "tests.test_llm_adapters_comprehensive.TestOpenAIAdapter#test_openai_adapter_authentication_error", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "parentSuite", "value": "tests"}, {"name": "suite", "value": "test_llm_adapters_comprehensive"}, {"name": "subSuite", "value": "TestOpenAIAdapter"}, {"name": "host", "value": "Joshuas-MacBook-Pro-2.local"}, {"name": "thread", "value": "33649-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.test_llm_adapters_comprehensive"}], "titlePath": ["tests", "test_llm_adapters_comprehensive.py", "TestOpenAIAdapter"]}