{"name": "test_connection_timeout[OpenAIAdapter-gpt-4]", "status": "passed", "description": "Test handling of connection timeouts", "attachments": [{"name": "log", "source": "c9808d42-9a25-41d0-91dd-0d7837976a34-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "adapter_class", "value": "<class 'app.services.llm_adapters.OpenAIAdapter'>"}, {"name": "model", "value": "'gpt-4'"}], "start": 1757657445062, "stop": 1757657445062, "uuid": "c88c7d13-91bd-46ff-bc32-837a294112d0", "historyId": "c50371b1e9be678476f086ebbc3a13bd", "testCaseId": "ba9cd9bb1e60e0917f6d0c6ca20e3841", "fullName": "tests.unit.test_llm_adapters_comprehensive.TestAdapterErrorScenarios#test_connection_timeout", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "parentSuite", "value": "tests.unit"}, {"name": "suite", "value": "test_llm_adapters_comprehensive"}, {"name": "subSuite", "value": "TestAdapterErrorScenarios"}, {"name": "host", "value": "Joshuas-MacBook-Pro-2.local"}, {"name": "thread", "value": "59211-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.test_llm_adapters_comprehensive"}], "titlePath": ["tests", "unit", "test_llm_adapters_comprehensive.py", "TestAdapterErrorScenarios"]}