{"name": "test_connection_timeout[OpenAIAdapter-gpt-4]", "status": "passed", "description": "Test handling of connection timeouts", "attachments": [{"name": "log", "source": "bc216333-2bac-47bd-b3e2-225748385c4b-attachment.txt", "type": "text/plain"}], "parameters": [{"name": "adapter_class", "value": "<class 'app.services.llm_adapters.OpenAIAdapter'>"}, {"name": "model", "value": "'gpt-4'"}], "start": 1757656656429, "stop": 1757656656430, "uuid": "e6a8de46-5261-4fa9-95c4-d874b11590c1", "historyId": "c50371b1e9be678476f086ebbc3a13bd", "testCaseId": "ba9cd9bb1e60e0917f6d0c6ca20e3841", "fullName": "tests.unit.test_llm_adapters_comprehensive.TestAdapterErrorScenarios#test_connection_timeout", "labels": [{"name": "tag", "value": "asyncio"}, {"name": "parentSuite", "value": "tests.unit"}, {"name": "suite", "value": "test_llm_adapters_comprehensive"}, {"name": "subSuite", "value": "TestAdapterErrorScenarios"}, {"name": "host", "value": "Joshuas-MacBook-Pro-2.local"}, {"name": "thread", "value": "30572-MainThread"}, {"name": "framework", "value": "pytest"}, {"name": "language", "value": "cpython3"}, {"name": "package", "value": "tests.unit.test_llm_adapters_comprehensive"}], "titlePath": ["tests", "unit", "test_llm_adapters_comprehensive.py", "TestAdapterErrorScenarios"]}